from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('seats','0022_seat_venue_role')]
    operations=[
        migrations.CreateModel(name='PersonnelLevel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80,unique=True,verbose_name='行政级别')),('order',models.PositiveIntegerField(db_index=True,default=100,verbose_name='排序')),('active',models.BooleanField(default=True,verbose_name='启用'))],options={'ordering':['order','id']}),
        migrations.CreateModel(name='PoliceDepartment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True,verbose_name='警种部门')),('short_name',models.CharField(blank=True,default='',max_length=80,verbose_name='桌牌名称')),('order',models.PositiveIntegerField(db_index=True,default=100,verbose_name='警种排序')),('active',models.BooleanField(default=True,verbose_name='启用'))],options={'ordering':['order','id']}),
        migrations.CreateModel(name='Participant',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80,verbose_name='姓名')),('category',models.CharField(choices=[('bureau_leader','局领导'),('attendee','列席人员'),('department','警种部门')],db_index=True,default='department',max_length=24,verbose_name='人员类别')),('position',models.CharField(blank=True,default='',max_length=120,verbose_name='职务')),('leader_order',models.PositiveIntegerField(default=100,verbose_name='局领导顺序')),('attendee_order',models.PositiveIntegerField(default=100,verbose_name='列席顺序')),('personal_order',models.PositiveIntegerField(default=100,verbose_name='同条件个人顺序')),('active',models.BooleanField(default=True,verbose_name='启用')),('remark',models.CharField(blank=True,default='',max_length=255,verbose_name='备注')),('department',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='participants',to='seats.policedepartment',verbose_name='警种部门')),('personnel_level',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='participants',to='seats.personnellevel',verbose_name='行政级别'))]),
        migrations.CreateModel(name='Meeting',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160,verbose_name='会议名称')),('meeting_date',models.DateField(blank=True,null=True,verbose_name='会议日期')),('use_stage',models.BooleanField(default=False,verbose_name='使用主席台')),('stage_mode',models.CharField(choices=[('auto','自动'),('specified','指定')],default='specified',max_length=16,verbose_name='主席台人员方式')),('created_at',models.DateTimeField(auto_now_add=True)),('venue',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='meetings',to='seats.classroom',verbose_name='会场'))]),
        migrations.CreateModel(name='MeetingParticipant',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('is_stage',models.BooleanField(default=False,verbose_name='主席台人员')),('include',models.BooleanField(default=True,verbose_name='参加本次会议')),('meeting',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='meeting_participants',to='seats.meeting')),('participant',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='meeting_participations',to='seats.participant'))]),
        migrations.AddField(model_name='meeting',name='participants',field=models.ManyToManyField(related_name='meetings',through='seats.MeetingParticipant',to='seats.participant')),
        migrations.CreateModel(name='MeetingSeatAssignment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('locked',models.BooleanField(default=False,verbose_name='锁定')),('skipped',models.BooleanField(default=False,verbose_name='跳过')),('sort_order',models.PositiveIntegerField(default=0,verbose_name='排座序号')),('meeting',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assignments',to='seats.meeting')),('participant',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='seat_assignments',to='seats.participant')),('seat',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='meeting_assignments',to='seats.seat'))]),
        migrations.AddConstraint(model_name='meetingparticipant',constraint=models.UniqueConstraint(fields=('meeting','participant'),name='unique_meeting_participant')),
        migrations.AddConstraint(model_name='meetingseatassignment',constraint=models.UniqueConstraint(fields=('meeting','seat'),name='unique_meeting_seat')),
        migrations.AddConstraint(model_name='meetingseatassignment',constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull',False)),fields=('meeting','participant'),name='unique_meeting_person_seat')),
    ]