from django.urls import path
from . import meeting_views as views

# 会场排排座离线版仅暴露会议业务入口；旧插件、AI、云端和数据共享路由不再加载。
urlpatterns = [
    path('', views.meeting_home, name='index'),
    path('meetings/', views.meeting_home, name='meeting_home'),
    path('people/', views.participant_library, name='participant_library'),
    path('history/', views.meeting_history, name='meeting_history'),
    path('settings/', views.meeting_settings, name='meeting_settings'),
    path('meetings/create/', views.meeting_create, name='meeting_create'),
    path('meetings/<int:pk>/', views.meeting_detail, name='meeting_detail'),
    path('meetings/<int:pk>/arrange/', views.meeting_arrange, name='meeting_arrange'),
    path('meetings/<int:pk>/participant/<int:participant_id>/state/', views.meeting_participant_state, name='meeting_participant_state'),
    path('meetings/<int:pk>/swap/', views.meeting_swap_seats, name='meeting_swap_seats'),
    path('meetings/<int:pk>/cards/', views.meeting_print_cards, name='meeting_print_cards'),
    path('meetings/<int:pk>/print/', views.meeting_print_chart, name='meeting_print_chart'),
    path('meeting-data/desk-cards/settings/', views.desk_card_template_update, name='desk_card_template_update'),
    path('meeting-data/backup/', views.local_backup_download, name='local_backup_download'),
    path('meeting-data/restore/', views.local_backup_restore, name='local_backup_restore'),
    path('meetings/<int:pk>/seat/<int:seat_id>/state/', views.meeting_seat_state, name='meeting_seat_state'),
    path('meeting-data/participants/create/', views.participant_create, name='participant_create'),
    path('meeting-data/participants/<int:participant_id>/edit/', views.participant_edit, name='participant_edit'),
    path('meeting-data/participants/<int:participant_id>/update/', views.participant_update, name='participant_update'),
    path('meeting-data/departments/<int:department_id>/update/', views.department_update, name='department_update'),
    path('meeting-data/levels/<int:level_id>/update/', views.level_update, name='level_update'),
    path('meetings/<int:pk>/edit/', views.meeting_edit, name='meeting_edit'),
    path('meeting-data/participants/<int:participant_id>/toggle/', views.participant_toggle, name='participant_toggle'),
    path('meeting-data/participants/export/', views.participants_export, name='participants_export'),
    path('meeting-data/participants/import/', views.participants_import, name='participants_import'),
    path('meetings/<int:pk>/update/', views.meeting_update, name='meeting_update'),
    path('meetings/<int:pk>/delete/', views.meeting_delete, name='meeting_delete'),
    path('meeting-data/departments/create/', views.department_create, name='department_create'),
    path('meeting-data/levels/create/', views.level_create, name='level_create'),
]
