"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from app_paths import database_path, plugin_directories
from database_security import database_encryption_enabled

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-1bux7tnh9ubww-d(pohhj#nw=n5ndw-&8tvns(!yx-pb*sn3xz'
DEBUG = True

ALLOWED_HOSTS = ['*']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'seats.apps.SeatsConfig',
]

APP_SHELL = os.getenv('FUCKSEATS_APP_SHELL', 'browser').strip() or 'browser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'seats.data_sharing.DataSharingUsageMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
            'seats.context_processors.app_runtime',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': (
            'config.sqlcipher_backend'
            if database_encryption_enabled()
            else 'django.db.backends.sqlite3'
        ),
        'NAME': database_path(),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


PLUGIN_DIRS = plugin_directories()
PLUGIN_MARKETPLACE_URL = os.getenv('PLUGIN_MARKETPLACE_URL', '').strip()
PLUGIN_REQUIRE_TRUSTED_SIGNATURE = os.getenv(
    'PLUGIN_REQUIRE_TRUSTED_SIGNATURE', '0'
).strip().lower() in {'1', 'true', 'yes', 'on'}

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '').strip()
OPENAI_BASE_URL = os.getenv('OPENAI_BASE_URL', '').strip()
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4.1-mini').strip() or 'gpt-4.1-mini'
WENDAO_AI_URL = 'https://ai.577622.xyz'

# 原有 AI 赋能工作台和聊天接口保持关闭；Open API 的 AI 类工具单独开放，
# 供外部 AI 工具调用班级能力和同步操作状态。
AI_FEATURE_ENABLED = False
OPEN_API_AI_TOOLS_ENABLED = os.getenv(
    'OPEN_API_AI_TOOLS_ENABLED',
    '1',
).strip().lower() not in {'0', 'false', 'no', 'off'}
